Repository mailchimp/mc-magento, pull requests merged in 2020-03, with the labels that each got.

#1151 Solved issue with inArray jquery method
  js/ebizmarts/mailchimp/campaignCatcher.js
Labels: bug

#1153 variable mcEid removed from observer and CampaignCatcher
  app/code/community/Ebizmarts/MailChimp/Model/Observer.php
  dev/tests/mailchimp/tests/app/Ebizmarts/MailChimp/Model/ObserverTest.php
  js/ebizmarts/mailchimp/campaignCatcher.js
Labels: bug

#1148 Update customer merge fields 1110
  app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers/MailchimpTags.php
  app/code/community/Ebizmarts/MailChimp/Model/ProcessWebhook.php
  dev/tests/mailchimp/tests/app/Ebizmarts/MailChimp/Model/Api/Subscribers/MailchimpTagsTest.php
  dev/tests/mailchimp/tests/app/Ebizmarts/MailChimp/Model/ProcessWebhookTest.php
Labels: enhancement

#1150 MapFields length limited in magento size to 10
  app/code/community/Ebizmarts/MailChimp/Block/Adminhtml/System/Config/Form/Field/Mapfields.php
Labels: bug

#1149 Only 10 interest group checkboxes showed after checkout
  app/code/community/Ebizmarts/MailChimp/Helper/Data.php
Labels: enhancement

#1168 Fix Mandrill info data.
  app/code/community/Ebizmarts/MailChimp/Helper/Curl.php
  lib/Mandrill/Mandrill.php
Labels: bug, done
